#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/.." && pwd)
fixture_template="$repo_root/fixtures/deterministic-turn"
run_root="$repo_root/tmp/deterministic-lab/latest"
workspace="$run_root/workspace"
artifacts="$run_root/artifacts"
codex_home="$run_root/codex-home"

if ! command -v codex >/dev/null 2>&1; then
  printf 'codex CLI not found on PATH\n' >&2
  exit 127
fi

case "$run_root" in
  "$repo_root"/tmp/deterministic-lab/latest) ;;
  *)
    printf 'refusing to clean unexpected run directory: %s\n' "$run_root" >&2
    exit 1
    ;;
esac

rm -rf "$run_root"
mkdir -p "$workspace" "$artifacts" "$codex_home"
cp -R "$fixture_template"/. "$workspace"/

if command -v git >/dev/null 2>&1; then
  git -C "$workspace" init -q
fi

run_prompt_input() {
  local name=$1
  local cwd=$2
  local prompt=$3
  local output="$artifacts/$name.prompt-input.json"

  CODEX_HOME="$codex_home" codex -C "$cwd" debug prompt-input "$prompt" > "$output"
  printf '%s\n' "$output"
}

assert_contains() {
  local file=$1
  local pattern=$2

  if ! rg -q "$pattern" "$file"; then
    printf 'expected %s to contain %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

assert_not_contains() {
  local file=$1
  local pattern=$2

  if rg -q "$pattern" "$file"; then
    printf 'expected %s not to contain %s\n' "$file" "$pattern" >&2
    exit 1
  fi
}

root_prompt=$(run_prompt_input \
  root \
  "$workspace" \
  "Edit src/sample.txt by appending LAB_ROOT_TOUCH.")

nested_prompt=$(run_prompt_input \
  nested \
  "$workspace/nested" \
  "Edit sample.txt by appending LAB_NESTED_TOUCH.")

mv "$workspace/AGENTS.md" "$workspace/AGENTS.disabled.md"
root_negative_prompt=$(run_prompt_input \
  root-negative \
  "$workspace" \
  "Edit src/sample.txt by appending LAB_ROOT_TOUCH.")

assert_contains "$root_prompt" "ROOT_AGENT_SENTINEL"
assert_not_contains "$root_prompt" "NESTED_AGENT_SENTINEL"
assert_contains "$nested_prompt" "ROOT_AGENT_SENTINEL"
assert_contains "$nested_prompt" "NESTED_AGENT_SENTINEL"
assert_not_contains "$root_negative_prompt" "ROOT_AGENT_SENTINEL"

cat > "$artifacts/README.md" <<REPORT
# Deterministic Lab Artifacts

Generated by \`scripts/run-deterministic-lab.sh\`.

Workspace copy:

\`\`\`text
$workspace
\`\`\`

Prompt input artifacts:

- \`root.prompt-input.json\`: root fixture prompt input.
- \`nested.prompt-input.json\`: nested fixture prompt input. In the current Codex behavior this includes both root and nested \`AGENTS.md\` instructions.
- \`root-negative.prompt-input.json\`: root prompt input after root \`AGENTS.md\` was renamed.

The runner uses an isolated \`CODEX_HOME\` at:

\`\`\`text
$codex_home
\`\`\`

That prevents user-level Codex instructions from leaking into the deterministic fixture.
REPORT

printf 'deterministic lab passed\n'
printf 'artifacts: %s\n' "$artifacts"
